services:
  - type: web
    name: securebypay-fullstack
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_SWAGGER
        value: "true"

